### ISSUE TITLE
Add a manifest file for each ecosystem

### ISSUE THREAD

**Issue by ikretz** [DataDog/malicious-software-packages-dataset#44]
Currently, there is no easy way to get an overview of which packages, and which versions of these packages, are in the dataset.  To make this easier, we should add a per-ecosystem text or JSON manifest file:

```text
libcraftsuperre 10.62
pycrypterexe 1.1.1 1.1.0 1.0.1 1.0.0 1.0.4 1.0.5 1.0.7 1.0.6 1.0.9 1.1.3 0.0.0
```
The CI job can automatically update the manifests as new samples are added.

**Comment by lionheart-mayank** [comment]
can you please tell me how to download this dataset and convert into data.csv to train model i need them urgently i am doing my course work in university
